version: "3.8"

services:
  web:
    build:
      context: ./frontend
      dockerfile: local.Dockerfile
    volumes:
      - ./frontend:/code
      - /code/node_modules/
    ports:
      - 3000:3000
    environment:
      NUXT_BASE_URL: http://api:8000/api
    depends_on:
      - api

  api:
    build:
      context: ./backend
      dockerfile: local.Dockerfile
    volumes:
      - ./backend:/code
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    ports:
      - 8000:8000
      - 5678:5678
    environment:
      SQLALCHEMY_DATABASE_URI: postgresql://postgres:postgres@db:5432/db
    depends_on:
      - db

  db:
    image: postgres:16.0-alpine3.18
    volumes:
      - .pgdata:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: db
